# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 738354707ccad1f893afd079511eec3fcb21e78603c6f8ab5cab2edae58f9174cafa252cee489e3548384d1035067318042b70373ba7d72461574e27542cf254

test:
  secret_key_base: c4ac48432ea57e8decff8b5f7327645f05680e673b6dcb4030606a0c2aa83189fa80e7ae5a6a09751020c6e3471221ab5884f16cdf92567e63d3e9faa44e87b4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
